### ISSUE TITLE
Suggest/make additional changes at the end of the tutorial

### ISSUE THREAD

**Issue by treyhunner** [pythonsd/test-driven-django-development#14]
Ideas:
- [ ] Allow posts to be drafted and only visible once they're "published"
- [ ] Limit the number of posts on the homepage (#11)
- [x] Use friendly slug-based URLs (#12)
- [x] Show post history in sidebar (#10)
